[options]
girs_dir = "gir-files"
library = "ModemManager"
version = "1.0"
#min_cfg_version = "1.2"
target_path = "."
work_mode = "normal"
single_version_file = true

generate = [
    "ModemManager.*",
    "ModemManager.Bearer",
    "ModemManager.BearerAllowedAuth",
    "ModemManager.BearerIpConfig",
    "ModemManager.BearerIpFamily",
    "ModemManager.BearerIpMethod",
    "ModemManager.BearerProperties",
    "ModemManager.BearerStats",
    "ModemManager.BearerType",
    "ModemManager.Call",
    "ModemManager.CallAudioFormat",
    "ModemManager.CallDirection",
    "ModemManager.CallProperties",
    "ModemManager.CallState",
    "ModemManager.CallStateReason",
    "ModemManager.CdmaActivationError",
    "ModemManager.CdmaManualActivationProperties",
    "ModemManager.ConnectionError",
    "ModemManager.CoreError",
    "ModemManager.FirmwareImageType",
    "ModemManager.FirmwareProperties",
    "ModemManager.FirmwareUpdateSettings",
    "ModemManager.GdbusBearer",
    "ModemManager.GdbusBearerProxy",
    "ModemManager.GdbusBearerSkeleton",
    "ModemManager.GdbusModem",
    "ModemManager.GdbusModem3gpp",
    "ModemManager.GdbusModem3gppProxy",
    "ModemManager.GdbusModem3gppSkeleton",
    "ModemManager.GdbusModem3gppUssd",
    "ModemManager.GdbusModem3gppUssdProxy",
    "ModemManager.GdbusModem3gppUssdSkeleton",
    "ModemManager.GdbusModemCdma",
    "ModemManager.GdbusModemCdmaProxy",
    "ModemManager.GdbusModemCdmaSkeleton",
    "ModemManager.GdbusModemFirmware",
    "ModemManager.GdbusModemFirmwareProxy",
    "ModemManager.GdbusModemFirmwareSkeleton",
    "ModemManager.GdbusModemLocation",
    "ModemManager.GdbusModemLocationProxy",
    "ModemManager.GdbusModemLocationSkeleton",
    "ModemManager.GdbusModemMessaging",
    "ModemManager.GdbusModemMessagingProxy",
    "ModemManager.GdbusModemMessagingSkeleton",
    "ModemManager.GdbusModemOma",
    "ModemManager.GdbusModemOmaProxy",
    "ModemManager.GdbusModemOmaSkeleton",
    "ModemManager.GdbusModemProxy",
    "ModemManager.GdbusModemSignal",
    "ModemManager.GdbusModemSignalProxy",
    "ModemManager.GdbusModemSignalSkeleton",
    "ModemManager.GdbusModemSimple",
    "ModemManager.GdbusModemSimpleProxy",
    "ModemManager.GdbusModemSimpleSkeleton",
    "ModemManager.GdbusModemSkeleton",
    "ModemManager.GdbusModemTime",
    "ModemManager.GdbusModemTimeProxy",
    "ModemManager.GdbusModemTimeSkeleton",
    "ModemManager.GdbusModemVoice",
    "ModemManager.GdbusModemVoiceProxy",
    "ModemManager.GdbusModemVoiceSkeleton",
    "ModemManager.GdbusObject",
    "ModemManager.GdbusObjectManagerClient",
    "ModemManager.GdbusObjectProxy",
    "ModemManager.GdbusObjectSkeleton",
    "ModemManager.GdbusOrgFreedesktopModemManager1",
    "ModemManager.GdbusOrgFreedesktopModemManager1Proxy",
    "ModemManager.GdbusOrgFreedesktopModemManager1Skeleton",
    "ModemManager.GdbusSim",
    "ModemManager.GdbusSimProxy",
    "ModemManager.GdbusSimSkeleton",
    "ModemManager.GdbusSms",
    "ModemManager.GdbusSmsProxy",
    "ModemManager.GdbusSmsSkeleton",
    "ModemManager.KernelEventProperties",
    "ModemManager.Location3gpp",
    "ModemManager.LocationCdmaBs",
    "ModemManager.LocationGpsNmea",
    "ModemManager.LocationGpsRaw",
    "ModemManager.Manager",
    "ModemManager.MessageError",
    "ModemManager.MobileEquipmentError",
    "ModemManager.Modem",
    "ModemManager.Modem3gpp",
    "ModemManager.Modem3gppEpsUeModeOperation",
    "ModemManager.Modem3gppFacility",
#    "ModemManager.Modem3gppNetwork",
    "ModemManager.Modem3gppNetworkAvailability",
    "ModemManager.Modem3gppRegistrationState",
    "ModemManager.Modem3gppSubscriptionState",
    "ModemManager.Modem3gppUssd",
    "ModemManager.Modem3gppUssdSessionState",
    "ModemManager.ModemAccessTechnology",
    "ModemManager.ModemBand",
    "ModemManager.ModemCapability",
    "ModemManager.ModemCdma",
    "ModemManager.ModemCdmaActivationState",
    "ModemManager.ModemCdmaRegistrationState",
    "ModemManager.ModemCdmaRmProtocol",
    "ModemManager.ModemContactsStorage",
    "ModemManager.ModemFirmware",
    "ModemManager.ModemFirmwareUpdateMethod",
    "ModemManager.ModemLocation",
    "ModemManager.ModemLocationAssistanceDataType",
    "ModemManager.ModemLocationSource",
    "ModemManager.ModemLock",
    "ModemManager.ModemMessaging",
    "ModemManager.ModemMode",
#    "ModemManager.ModemModeCombination",
    "ModemManager.ModemOma",
#    "ModemManager.ModemPortInfo",
    "ModemManager.ModemPortType",
    "ModemManager.ModemPowerState",
    "ModemManager.ModemSignal",
    "ModemManager.ModemSimple",
    "ModemManager.ModemState",
    "ModemManager.ModemStateChangeReason",
    "ModemManager.ModemStateFailedReason",
    "ModemManager.ModemTime",
    "ModemManager.ModemVoice",
    "ModemManager.NetworkTimezone",
    "ModemManager.Object",
    "ModemManager.OmaFeature",
#    "ModemManager.OmaPendingNetworkInitiatedSession",
    "ModemManager.OmaSessionState",
    "ModemManager.OmaSessionStateFailedReason",
    "ModemManager.OmaSessionType",
    "ModemManager.Pco",
    "ModemManager.SerialError",
    "ModemManager.Signal",
    "ModemManager.Sim",
    "ModemManager.SimpleConnectProperties",
    "ModemManager.SimpleStatus",
    "ModemManager.Sms",
    "ModemManager.SmsCdmaServiceCategory",
    "ModemManager.SmsCdmaTeleserviceId",
    "ModemManager.SmsDeliveryState",
    "ModemManager.SmsPduType",
    "ModemManager.SmsProperties",
    "ModemManager.SmsState",
    "ModemManager.SmsStorage",
    "ModemManager.SmsValidityType",
    "ModemManager.UnlockRetries",
    "ModemManager.UnlockRetriesForeachCb",
]

manual = [
    "GObject.Object",
    "GLib.ByteArray",
    "GLib.Bytes",
    "GLib.FileTest",
    "GLib.Error",
    "GLib.KeyFile",
    "GLib.ObjectClass",
    "GLib.PtrArray",
    "GLib.Variant",
    "GLib.VariantType",
    "Gio.AsyncReadyCallback",
    "Gio.Cancellable",
    "Gio.DBusConnection",
    "Gio.DBusInterfaceInfo",
    "Gio.DBusMethodInvocation",
    "Gio.DBusObjectManagerClientFlags",
    "Gio.DBusProxy",
    "Gio.InputStream",
    "Gio.OutputStream",
]
