[options]
girs_dir = "gir-files"
library = "ModemManager"
version = "1.0"
#min_cfg_version = "1.2"
target_path = "."
work_mode = "normal"
single_version_file = true

generate = [
    "ModemManager.*",
    "ModemManager.Bearer",
    "ModemManager.BearerIpConfig",
    "ModemManager.BearerProperties",
    "ModemManager.BearerStats",
    "ModemManager.Call",
    "ModemManager.CallAudioFormat",
    "ModemManager.CallProperties",
    "ModemManager.CdmaManualActivationProperties",
    "ModemManager.FirmwareProperties",
    "ModemManager.FirmwareUpdateSettings",
    "ModemManager.GdbusBearer",
    "ModemManager.GdbusBearerProxy",
    "ModemManager.GdbusBearerSkeleton",
    "ModemManager.GdbusModem",
    "ModemManager.GdbusModem3gpp",
    "ModemManager.GdbusModem3gppProxy",
    "ModemManager.GdbusModem3gppSkeleton",
    "ModemManager.GdbusModem3gppUssd",
    "ModemManager.GdbusModem3gppUssdProxy",
    "ModemManager.GdbusModem3gppUssdSkeleton",
    "ModemManager.GdbusModemCdma",
    "ModemManager.GdbusModemCdmaProxy",
    "ModemManager.GdbusModemCdmaSkeleton",
    "ModemManager.GdbusModemFirmware",
    "ModemManager.GdbusModemFirmwareProxy",
    "ModemManager.GdbusModemFirmwareSkeleton",
    "ModemManager.GdbusModemLocation",
    "ModemManager.GdbusModemLocationProxy",
    "ModemManager.GdbusModemLocationSkeleton",
    "ModemManager.GdbusModemMessaging",
    "ModemManager.GdbusModemMessagingProxy",
    "ModemManager.GdbusModemMessagingSkeleton",
    "ModemManager.GdbusModemOma",
    "ModemManager.GdbusModemOmaProxy",
    "ModemManager.GdbusModemOmaSkeleton",
    "ModemManager.GdbusModemProxy",
    "ModemManager.GdbusModemSignal",
    "ModemManager.GdbusModemSignalProxy",
    "ModemManager.GdbusModemSignalSkeleton",
    "ModemManager.GdbusModemSimple",
    "ModemManager.GdbusModemSimpleProxy",
    "ModemManager.GdbusModemSimpleSkeleton",
    "ModemManager.GdbusModemSkeleton",
    "ModemManager.GdbusModemTime",
    "ModemManager.GdbusModemTimeProxy",
    "ModemManager.GdbusModemTimeSkeleton",
    "ModemManager.GdbusModemVoice",
    "ModemManager.GdbusModemVoiceProxy",
    "ModemManager.GdbusModemVoiceSkeleton",
    "ModemManager.GdbusObject",
    "ModemManager.GdbusObjectManagerClient",
    "ModemManager.GdbusObjectProxy",
    "ModemManager.GdbusObjectSkeleton",
    "ModemManager.GdbusOrgFreedesktopModemManager1",
    "ModemManager.GdbusOrgFreedesktopModemManager1Proxy",
    "ModemManager.GdbusOrgFreedesktopModemManager1Skeleton",
    "ModemManager.GdbusSim",
    "ModemManager.GdbusSimProxy",
    "ModemManager.GdbusSimSkeleton",
    "ModemManager.GdbusSms",
    "ModemManager.GdbusSmsProxy",
    "ModemManager.GdbusSmsSkeleton",
    "ModemManager.KernelEventProperties",
    "ModemManager.Location3gpp",
    "ModemManager.LocationCdmaBs",
    "ModemManager.LocationGpsNmea",
    "ModemManager.LocationGpsRaw",
    "ModemManager.Manager",
    "ModemManager.Modem",
    "ModemManager.Modem3gpp",
    "ModemManager.Modem3gppNetwork",
    "ModemManager.Modem3gppUssd",
    "ModemManager.ModemCdma",
    "ModemManager.ModemFirmware",
    "ModemManager.ModemLocation",
    "ModemManager.ModemMessaging",
    "ModemManager.ModemModeCombination",
    "ModemManager.ModemOma",
    "ModemManager.ModemPortInfo",
    "ModemManager.ModemSignal",
    "ModemManager.ModemSimple",
    "ModemManager.ModemTime",
    "ModemManager.ModemVoice",
    "ModemManager.NetworkTimezone",
    "ModemManager.Object",
    "ModemManager.OmaPendingNetworkInitiatedSession",
    "ModemManager.Pco",
    "ModemManager.Signal",
    "ModemManager.Sim",
    "ModemManager.SimpleConnectProperties",
    "ModemManager.SimpleStatus",
    "ModemManager.Sms",
    "ModemManager.SmsProperties",
    "ModemManager.UnlockRetries",
]

manual = [
    "GObject.Object",
    "GLib.Bytes",
    "GLib.FileTest",
    "GLib.Error",
    "GLib.KeyFile",
    "GLib.PtrArray",
    "GLib.Variant",
    "GLib.VariantType",
    "Gio.AsyncReadyCallback",
    "Gio.Cancellable",
    "Gio.InputStream",
    "Gio.OutputStream",
]
