#!/usr/bin/env python
# -*- coding: utf-8 -*-

import shutil
import os

def move_autogenerated():
    src = "src/auto"
    dst = "src"
    for name in os.listdir(src):
        src_name = os.path.join(src, name)
        dst_name = os.path.join(dst, name)
        shutil.move(src_name, dst_name)

    shutil.rmtree(src)

def read_auto_mod():
    src = "src/mod.rs"
    lines = []
    with open(src, "r") as f:
        while True:
            line = f.readline()
            if not line:
                break
            if line.startswith("//"):
                continue
            lines.append(line)
    os.remove(src)
    return lines

def append_lib(lines):
    src = "src/lib.rs"
    with open(src, "a") as f:
        f.writelines(lines)

def merge():
    move_autogenerated()
    lines = read_auto_mod()
    append_lib(lines)

merge()
