[package]
version = "0.4.0"
authors = ["majorz"]

[sys-dependencies]
libc = "0.2"
glib-sys = { git = "https://github.com/gtk-rs/gtk-rs-core" }
gio-sys = { git = "https://github.com/gtk-rs/gtk-rs-core" }
gobject-sys = { git = "https://github.com/gtk-rs/gtk-rs-core" }

[dependencies]
libc = "0.2"
once_cell = "1.5"
bitflags = "1.2"
futures-core = "0.3"
futures-task = "0.3"
futures-executor = "0.3"
futures-util = "0.3"
futures-channel = "0.3"
glib = { git = "https://github.com/gtk-rs/gtk-rs-core" }
glib-sys = { git = "https://github.com/gtk-rs/gtk-rs-core" }
gio = { git = "https://github.com/gtk-rs/gtk-rs-core" }
gio-sys = { git = "https://github.com/gtk-rs/gtk-rs-core" }
gobject-sys = { git = "https://github.com/gtk-rs/gtk-rs-core" }

[dev-dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.1"

[sys-build-dependencies]
system-deps = "1.3"

[sys-dev-dependencies]
shell-words = "0.1.0"
tempfile = "3"
