[package]
version = "0.3.0"
authors = ["majorz"]

[shared-dependencies]
libc = "0.2"
glib-sys = "0.9.1"
gio-sys = "0.9.1"
gobject-sys = "0.9.1"

[dependencies]
once_cell = "1.3"
bitflags = "1.0"
futures-core = "0.3"
futures-task = "0.3"
futures-executor = "0.3"
futures-util = "0.3"
futures-channel = "0.3"
glib = "0.9.1"
gio = "0.8.0"

[dev-dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.1"

[sys-build-dependencies]
system-deps = "1.3"

[sys-dev-dependencies]
shell-words = "0.1.0"
tempfile = "3"
